# Generated by Django 5.1 on 2024-08-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_signupdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupdata',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='signupdata',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='signupdata',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='signupdata',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
