# Generated by Django 5.1 on 2024-09-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_rename_phone_number_signupdata_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupdata',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
