# Generated by Django 5.1 on 2024-09-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_rename_phone_signupdata_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupdata',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
