# Generated by Django 5.1 on 2024-09-19 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
