# Generated by Django 5.1 on 2024-09-20 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0007_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignupData',
            new_name='SignupDetails',
        ),
    ]
