# Generated by Django 5.1 on 2024-09-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0010_signupdata_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='info',
            field=models.CharField(default=0, max_length=10000),
            preserve_default=False,
        ),
    ]
