# Generated by Django 5.1 on 2024-09-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0011_planet_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupData',
        ),
    ]
