# Generated by Django 5.1 on 2024-09-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0013_rocket'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocket',
            name='image',
            field=models.ImageField(default=0, upload_to='rocket/'),
            preserve_default=False,
        ),
    ]
